
# markdown: kramdown
highlighter: rouge

timezone: America/New_York

collections:
  docs:
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true

name: Example
description: Example Description
url: https://bs4live.com

logo: /img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - README.md
  - .gitignore
